apiVersion: apps/v1
kind: Deployment
metadata:
  name: modifica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modifica
  template:
    metadata:
      labels:
        app: modifica
    spec:
      containers:
        - name: modifica
          image: registry.default.svc.cluster.local:5000/lib-modifica:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_HOST
              value: postgres-modifica
            - name: POSTGRES_DB
              value: libreria_modifica
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: EVENT_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EVENT_EXCHANGE
            - name: MODIFICA_SYNC_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MODIFICA_SYNC_QUEUE
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS_ORIGINS
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 20
